### PR TITLE
HTTP client fixes

### LINKED ISSUE #2158: http_parser failing with HPE_CLOSED_CONNECTION
The problem is occuring running the UPnP scan tool https://github.com/mikee47/Sming-UPnP/tree/fix/scanner-updates/tools/scan.
The application is running in Host mode under Windows.

http_parser appears to be declaring the connection dead before the content has been processed.

It does not appear to be related to the size of the file being fetched.
The tool retries and sometimes succeeds, but there are a significant number which fail after 3 attempts.

Here is a log extract. It looks like the problem occurs as a result of `12478573 TCP 3e53968 connection closing`.

```
12358264 Received description
12359841 Writing out/upnp/devices/192.168.1.254/1900/gatedesc.xml
12363265 Opened file 'out/upnp/devices/192.168.1.254/1900/gatedesc.xml', 0 bytes
12376116 Writing out/upnp/schema/schemas-upnp-org/device/InternetGatewayDevice1.xml
12376640 Opened file 'out/upnp/schema/schemas-upnp-org/device/InternetGatewayDevice1.xml', 0 bytes
12385560 serviceList found
12414622 Writing out/upnp/schema/schemas-upnp-org/device/WANDevice1.xml
12418965 Opened file 'out/upnp/schema/schemas-upnp-org/device/WANDevice1.xml', 0 bytes
12420457 serviceList found
12445278 Writing out/upnp/schema/schemas-upnp-org/device/WANConnectionDevice1.xml
12448081 Opened file 'out/upnp/schema/schemas-upnp-org/device/WANConnectionDevice1.xml', 0 bytes
12457702 serviceList found
12478573 TCP 3e53968 connection closing
12480367 TCP 3e53968 received: 675 bytes
12481327 -TCP connection
14479905 Fetching '(service) http://192.168.1.254:1900/gateconnSCPD.xml' -> 'out/upnp/devices/192.168.1.254/1900/urn:schemas-upnp-org:service:WANIPConnection:1.xml''
14483388 Fetching description from URL: 'http://192.168.1.254:1900/gateconnSCPD.xml'
14489705 TCP 3e53968 +connection
14497519 TCP 3e53968 connect to "192.168.1.254:1900"
14499531 TCP connect result: 0
14500941 TCP 3e53968 connected: useSSL: 0, Error: 0
14505351 TCP 3e53968 connected
14506302 MemoryDataStream::realloc 0 -> 32
14511211 Storing 32 bytes in stream
14515110 MemoryDataStream::realloc 32 -> 186
14516623 Storing 26 bytes in stream
14519555 Storing 19 bytes in stream
14520969 Storing 2 bytes in stream
14525029 TCP 3e53968 onReadyToSendData: 0
14527349 TCP 3e53968 Written: 79, Available: 2780, isFinished: 0, PushCount: 1
14531706 TcpClient stream finished
14534160 TCP 3e53968 sent: 79
14537567 TCP 3e53968 onReadyToSendData: 2
14543533 HTTP parser error: HPE_CLOSED_CONNECTION
14545742 TcpClient::onReceive: Aborted from receive callback
```

The received header looks like this:

```
HTTP/1.1 200 OK
CONTENT-LENGTH: 12924
CONTENT-TYPE: text/xml
DATE: Mon, 30 Nov 2020 09:29:43 GMT
LAST-MODIFIED: Thu, 01 Jan 1970 00:00:19 GMT
SERVER: Linux/2.6.36.4brcmarm, UPnP/1.0, Portable SDK for UPnP devices/1.6.19
X-User-Agent: redsonic
CONNECTION: close
```

### PR DESCRIPTION
**Pull request by mikee47**
- Improvements to pipelining.
- Improvements to retrying the current request(as is the case for URLs protected with digest authentication).
- Fixed post requests sending files and/or form data.
- Small improvements to the handing of failed writes in TcpConnection.

### CODE REVIEW

**Comment by slaff** [comment]
@mikee47 Added one more commit to this PR which addresses possible problems caused by pipelining https://github.com/SmingHub/Sming/pull/2163/commits/3a248f9dbcea3e3f89084c119b7eb5976e3adf4f . Can you take a look at it and test it on your Windows or Linux VM  machine?

**Comment by mikee47** [comment]
@slaff Looks fine, works well! Thank you.

File: Sming/Core/Data/Stream/MultipartStream.h [hunk 1]
```diff
@@ -60,6 +60,7 @@ class MultipartStream : public MultiStream
 	Producer producer;
 	BodyPart bodyPart;
 	char boundary[16] = {0};
+	bool finished = false;
```
Comment (mikee47) [inline Sming/Core/Data/Stream/MultipartStream.h:63]: This shadows MultiStream::finished...

**Comment by slaff** [comment]
@mikee47 While trying to make the HttpClient work again I have noticed that the LimitedMemoryStream was broken in this PR #2119.

The changes in the isFinished(), given below
```C++
	bool isFinished() override
	{
		return (readPos >= capacity);
	}
```

cause endless loop when trying to copy the data:
```
size_t ReadWriteStream::copyFrom(IDataSourceStream* source, size_t size)
{
	if(source == nullptr || size == 0) {
		return 0;
	}

	auto bufSize = std::min(size, maxBufferSize);
	char buffer[bufSize];
	size_t total = 0;
	size_t count;
	while(!source->isFinished()) {
		count = source->readMemoryBlock(buffer, sizeof(buffer));
		if(count == 0) {
			continue;
		}
		auto written = write(reinterpret_cast<uint8_t*>(buffer), count);
		source->seek(written);
		total += count;
		if(written != count) {
			break;
		}
	}

	return total;
}
```

called from here:
```C++
int onDownload(HttpConnection& connection, bool success)
{
	debugf("\n=========[ URL: %s ]============", connection.getRequest()->uri.toString().c_str());
	debugf("RemoteIP: %s", connection.getRemoteIp().toString().c_str());
	debugf("Got response code: %d", connection.getResponse()->code);
	debugf("Success: %d", success);
	if(connection.getRequest()->method != HTTP_HEAD) {
		Serial.print(_F("Got content: "));
		auto stream = connection.getResponse()->stream;
		if(stream == nullptr || stream->available() == 0) {
			Serial.println("EMPTY!");
		} else {
			Serial.copyFrom(stream);
```

IMHO the isFinished method here should be just:
```C++
	bool isFinished() override
	{
		return (available() == 0 );
	}
```

@mikee47 Can you create a separate PR with a fix?

File: Sming/Core/Network/Http/HttpClientConnection.cpp [hunk 2]
```diff
@@ -315,6 +315,7 @@ void HttpClientConnection::onClosed()
 		System.queueCallback([this]() {
 			cleanup();
 			init(HTTP_RESPONSE);
+			state = eHCS_Ready;
```
Comment (mikee47) [inline Sming/Core/Network/Http/HttpClientConnection.cpp:318]: Should this be done in `init()` ?

Comment (slaff) [reply Sming/Core/Network/Http/HttpClientConnection.cpp:318]: > Should this be done in init() ?

Yes, indeed. I will add this correction in a second...

**Comment by slaff** [comment]
@mikee47 There is a problem with SSL and sending data in the TcpConnection. I will address also this but it will be part of a separate PR.

**Comment by slaff** [comment]
@mikee47 Can you compile the latest code from this PR and test if you still have the problems described in #2158?

**Comment by mikee47** [comment]
@slaff I got the failed requests again, so re-tested with the previous working commit and still failing! So I increased the scanner `fetchInterval` from 250 to 500 (ms) and it started working again! However, behaviour with/without the task queue is the same; I re-checked in the debugger and the stack usage is minimal so looks like that isn't necessary and commit 8bb1312c is fine.

I then revisited the issue wth using the task queue in ControlPoint - https://github.com/mikee47/Sming-UPnP/blob/3e66a17cbd9c9287485a4a2b177a79a0744d2f64/src/ControlPoint.cpp#L211 onwards. The issue persists, and is definitely related to this issue. I need to improve the debug output so requests can be correlated with responses more easily, then perhaps the logs will shed more light on exactly what's happening...

**Comment by mikee47** [comment]
So at present we can retry sending headers but the body stream also needs to be recovered. I started attempting to fix that by restoring and resetting the stream (see commit for `StreamTransformer::seekFrom()`) but of course by that time it's been destroyed by the call to `freeStreams()` in `TcpClient::pushAsyncPart()`.

**Comment by slaff** [comment]
@mikee47 Once Travis is ready I will merge this PR in develop. It does not solve your problem but at least has some useful fixes. Any idea how I can reproduce the problem that your experiencing on my machine? This will help me go step by step with the debugger and correlate network traffic with live wireshark capture.

**Comment by mikee47** [comment]
@slaff I got the same issue running the Basic_ControlPoint sample on an ESP8266. I'll re-check to confirm and get back to you.

**Comment by slaff** [comment]
> I'll re-check to confirm and get back to you.

Get the latest develop and rebase on it. Compile your sample using the following commands (adjust accordingly ):
```
cd <sample-dir>
make config-clean
make dist-clean
make SMING_ARCH=Host ENABLE_GDB=1 DEBUG_VERBOSE_LEVEL=3 
```

**Comment by slaff** [comment]
> There is a problem with SSL and sending data in the TcpConnection. I will address also this but it will be part of a separate PR.

See #2173 .

**Comment by mikee47** [comment]
@slaff I've rebuilt and re-tested as follows:

```
cd %SMING_HOME%
make dist-clean
make fetch UPnP
cd Libraries\UPnP\samples\Basic_ControlPoint
make -j20 SMING_ARCH=Host ENABLE_GDB=1 DEBUG_VERBOSE_LEVEL=3
make run
```

The attached log `initial-run` shows the results of, all looks fine.

I then checked out the `fix/http-debugging` branch of UPnP d7ccee6e6f07b7742ae661bcd7a16978eda32e38:

```
make -j20 Sming-build all
make run
```

The results are in `controlpoint-task-queue`, and it should be visible that the response to the first action request gets lost in the HTTP connection closing business.

When a device has been discovered and created by ControlPoint, the client callback creates action requests and submits them.
The client should be able to successfully sent action requests at any time, so deferring the callback is a good test for this.
I've considered delaying the callback for a fixed time (e.g. 2 seconds) to allow any connection closing to complete - that's more of a workaround though and would just mask the problem.

[debug_logs.zip](https://github.com/SmingHub/Sming/files/5644598/debug_logs.zip)

The action requests are for `ContentDirectory` services on my archer VR900 router - it has a USB stick with audio files on it. See https://www.tp-link.com/uk/support/download/archer-vr900/v1/. Here's the relevant DD fields:

```
        <deviceType>urn:schemas-upnp-org:device:MediaServer:1</deviceType>
        <manufacturer>Justin Maggard</manufacturer>
        <manufacturerURL>http://www.tp-link.com/</manufacturerURL>
        <modelDescription>MiniDLNA on Linux</modelDescription>
        <modelName>Windows Media Connect compatible (MiniDLNA)</modelName>
        <X_DLNADOC xmlns:dlna="urn:schemas-dlna-org:device-1-0">DMS-1.50</X_DLNADOC>
```

You could probably run MiniDLNA on another device to check this - seems very unlikely it's the router which is the problem but I'll see if I can find an alternative device to test this against.
