### PR TITLE
Fix array bounds issue detected via GCC-8 on Host build

### LINKED ISSUE #1706: Array bounds warning building Host with GCC 8
See #1692 for initial problem report.

The issue is with the `LOAD_PSTR` macro in `FakePgmSpace.h`, which copies data from flash to RAM in 4-byte words. Byte-copying from flash is very inefficient so this is an optimisation for the Esp8266.

This issue has arised now we can compile the code using more up-to-date tools. From https://gcc.gnu.org/gcc-8/changes.html:

`The -Warray-bounds option has been improved to detect more instances of out-of-bounds array indices and pointer offsets. For example, negative or excessive indices into flexible array members and string literals are detected.`

This is the output from the pre-processor for the offending code:

```
  case EVENT_STAMODE_CONNECTED:
  (__extension__({
    static const char log_string[] = "%u " "connect to ssid %s, channel %d" "\r\n";
    char fmtbuf[(((sizeof(log_string)) + 3) & ~3)] __attribute__((aligned(4)));
    memcpy(fmtbuf, log_string, sizeof(fmtbuf));;
    m_printf(fmtbuf, system_get_time(), evt->event_info.connected.ssid, evt->event_info.connected.channel);
  }));
```

We're attempting to do a `memcpy` using the size of the allocated buffer, which is longer than the actual data stored in flash. That doesn't matter on the Esp8266 as we know it's safe to read at least to the next word boundary, but it's not good practice.

### PR DESCRIPTION
**Pull request by mikee47**
Closes #1706

* Change `memcpy_aligned` to use the non-aligned source data length. On Host platform it's just a regular `memcpy`, but for `Esp8266` we use the aligned length.
* Replace custom copying code with a regular `memcpy` call - it's actually faster.

Revise `memcmp_aligned` to behaves exactly like a regular `memcmp`, and consistent with memcpy_aligned.

Use implementations of `memcpy_aligned` and `memcmp_aligned` in Host build so they can be properly tested

* Define `PROGMEM` to ensure data is word-aligned
* Always compile `memcpy_aligned` and `memcmp_aligned`
* Use full `PSTR()` and `_F()` macros for Host

Builds and runs `HostTests` on Host/Esp8266 platforms.

### CODE REVIEW

**Comment by slaff** [comment]
I tried this PR with the Host architecture and now I am getting segfaults all over the place. 
Valgrind pointed out this as an issue for the DNSCaptivePortal sample :

```
main: >> Starting Sming <<

==31930== Source and destination overlap in memcpy(0x4435748, 0x4435748, 1)
==31930==    at 0x4030D39: memcpy (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==31930==    by 0x805F8EF: memcpy (string3.h:53)
==31930==    by 0x805F8EF: String::replace(String const&, String const&) (WString.cpp:692)
==31930==    by 0x8063891: DNSServer::downcaseAndRemoveWwwPrefix(String&) (DNSServer.cpp:42)
==31930==    by 0x8063904: DNSServer::start(unsigned short, String const&, IPAddress const&) (DNSServer.cpp:28)
==31930==    by 0x805D686: startServers() (application.cpp:24)
==31930==    by 0x805D2B5: FunctionCaller<void (*)(), void>::invoke() (Delegate.h:110)
==31930==    by 0x804B025: SystemClass::onReady(Delegate<void ()>)::{lambda(unsigned int)#1}::_FUN(unsigned int) (Delegate.h:172)
==31930==    by 0x804AFE7: SystemClass::taskHandler(os_event_t*) (System.cpp:34)
==31930==    by 0x804B327: process (tasks.cpp:37)
==31930==    by 0x804B327: host_service_tasks (tasks.cpp:84)
==31930==    by 0x804A254: main (startup.cpp:220)
==31930== 
```

and then that as the reason for the segfault:

```
==31930== Conditional jump or move depends on uninitialised value(s)
==31930==    at 0x424503B: tolower (ctype.c:46)
==31930==    by 0x402FD2B: strcasecmp (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==31930==    by 0x805F560: String::equalsIgnoreCase(FlashString const&) const (WString.cpp:499)
==31930==    by 0x80655EA: HttpHeaders::fromString(String const&) const (HttpHeaders.cpp:52)
==31930==    by 0x8064107: operator[] (HttpHeaders.h:149)
==31930==    by 0x8064107: onHeaderValue (HttpHeaderBuilder.h:35)
==31930==    by 0x8064107: HttpConnection::staticOnHeaderValue(http_parser*, char const*, unsigned int) (HttpConnection.cpp:124)
==31930==    by 0x806DD45: http_parser_execute (http_parser.c:1426)
==31930==    by 0x806405F: HttpConnection::onTcpReceive(TcpClient&, char*, int) (HttpConnection.cpp:177)
==31930==    by 0x8063E7F: MethodCaller<bool (HttpConnection::*)(TcpClient&, char*, int)>::invoke(TcpClient&, char*, int) (Delegate.h:83)
==31930==    by 0x80622C7: operator() (Delegate.h:172)
==31930==    by 0x80622C7: TcpClient::onReceive(pbuf*) (TcpClient.cpp:105)
==31930==    by 0x8061AEF: TcpConnection::internalOnReceive(pbuf*, signed char) (TcpConnection.cpp:572)
==31930==    by 0x8061BAB: TcpConnection::initialize(tcp_pcb*)::{lambda(void*, tcp_pcb*, pbuf*, signed char)#2}::_FUN(void*, tcp_pcb*, pbuf*, signed char) (TcpConnection.cpp:340)
==31930==    by 0x8054BDC: tcp_input (tcp_in.c:501)
==31930==  Uninitialised value was created by a stack allocation
==31930==    at 0x805F54E: String::equalsIgnoreCase(FlashString const&) const (WString.cpp:498)
==31930== 
==31930== Use of uninitialised value of size 4
==31930==    at 0x4245052: tolower (ctype.c:46)
==31930==    by 0x402FD2B: strcasecmp (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==31930==    by 0x805F560: String::equalsIgnoreCase(FlashString const&) const (WString.cpp:499)
==31930==    by 0x80655EA: HttpHeaders::fromString(String const&) const (HttpHeaders.cpp:52)
==31930==    by 0x8064107: operator[] (HttpHeaders.h:149)
==31930==    by 0x8064107: onHeaderValue (HttpHeaderBuilder.h:35)
==31930==    by 0x8064107: HttpConnection::staticOnHeaderValue(http_parser*, char const*, unsigned int) (HttpConnection.cpp:124)
==31930==    by 0x806DD45: http_parser_execute (http_parser.c:1426)
==31930==    by 0x806405F: HttpConnection::onTcpReceive(TcpClient&, char*, int) (HttpConnection.cpp:177)
==31930==    by 0x8063E7F: MethodCaller<bool (HttpConnection::*)(TcpClient&, char*, int)>::invoke(TcpClient&, char*, int) (Delegate.h:83)
==31930==    by 0x80622C7: operator() (Delegate.h:172)
==31930==    by 0x80622C7: TcpClient::onReceive(pbuf*) (TcpClient.cpp:105)
==31930==    by 0x8061AEF: TcpConnection::internalOnReceive(pbuf*, signed char) (TcpConnection.cpp:572)
==31930==    by 0x8061BAB: TcpConnection::initialize(tcp_pcb*)::{lambda(void*, tcp_pcb*, pbuf*, signed char)#2}::_FUN(void*, tcp_pcb*, pbuf*, signed char) (TcpConnection.cpp:340)
==31930==    by 0x8054BDC: tcp_input (tcp_in.c:501)
==31930==  Uninitialised value was created by a stack allocation
==31930==    at 0x805F54E: String::equalsIgnoreCase(FlashString const&) const (WString.cpp:498)
==31930== 
==31930== Invalid read of size 4
==31930==    at 0x806A20C: HttpResponse::freeStreams() (HttpResponse.cpp:172)
==31930==    by 0x806A304: HttpResponse::reset() (HttpResponse.cpp:163)
==31930==    by 0x8068184: HttpServerConnection::onReadyToSendData(TcpConnectionEvent) (HttpServerConnection.cpp:193)
==31930==    by 0x8061363: TcpConnection::onSent(unsigned short) (TcpConnection.cpp:125)
==31930==    by 0x80623D0: TcpClient::onSent(unsigned short) (TcpClient.cpp:175)
==31930==    by 0x8061BCE: TcpConnection::internalOnSent(unsigned short) (TcpConnection.cpp:589)
==31930==    by 0x8061C13: TcpConnection::initialize(tcp_pcb*)::{lambda(void*, tcp_pcb*, unsigned short)#1}::_FUN(void*, tcp_pcb*, unsigned short) (TcpConnection.cpp:324)
==31930==    by 0x8054B40: tcp_input (tcp_in.c:468)
==31930==    by 0x805BD08: ip4_input (ip4.c:709)
==31930==    by 0x805C589: ethernet_input (ethernet.c:186)
==31930==    by 0x805C907: tapif_input (tapif.c:326)
==31930==    by 0x805CBFA: tapif_select (tapif.c:398)
==31930==  Address 0x4438210 is 0 bytes inside a block of size 32 free'd
==31930==    at 0x402D7B8: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==31930==    by 0x8070C19: MemoryDataStream::~MemoryDataStream() (MemoryDataStream.h:34)
==31930==    by 0x8061E19: TcpClient::freeStreams() (TcpClient.cpp:24)
==31930==    by 0x8062117: TcpClient::pushAsyncPart() (TcpClient.cpp:162)
==31930==    by 0x8062332: TcpClient::onReadyToSendData(TcpConnectionEvent) (TcpClient.cpp:130)
==31930==    by 0x80681AB: HttpServerConnection::onReadyToSendData(TcpConnectionEvent) (HttpServerConnection.cpp:205)
==31930==    by 0x806131C: TcpConnection::onReceive(pbuf*) (TcpConnection.cpp:110)
==31930==    by 0x80622F1: TcpClient::onReceive(pbuf*) (TcpClient.cpp:118)
==31930==    by 0x8061AEF: TcpConnection::internalOnReceive(pbuf*, signed char) (TcpConnection.cpp:572)
==31930==    by 0x8061BAB: TcpConnection::initialize(tcp_pcb*)::{lambda(void*, tcp_pcb*, pbuf*, signed char)#2}::_FUN(void*, tcp_pcb*, pbuf*, signed char) (TcpConnection.cpp:340)
==31930==    by 0x8054BDC: tcp_input (tcp_in.c:501)
==31930==    by 0x805BD08: ip4_input (ip4.c:709)
==31930==  Block was alloc'd at
==31930==    at 0x402C6BC: operator new(unsigned int) (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==31930==    by 0x806A392: HttpResponse::sendString(String const&) (HttpResponse.cpp:60)
==31930==    by 0x805D2F2: onIndex(HttpRequest&, HttpResponse&) (application.cpp:11)
==31930==    by 0x805D2A7: FunctionCaller<void (*)(HttpRequest&, HttpResponse&), void, HttpRequest&, HttpResponse&>::invoke(HttpRequest&, HttpResponse&) (Delegate.h:110)
==31930==    by 0x806B59B: operator() (Delegate.h:172)
==31930==    by 0x806B59B: HttpCompatResource::requestComplete(HttpServerConnection&, HttpRequest&, HttpResponse&) (HttpResourceTree.cpp:26)
==31930==    by 0x806B5E3: MethodCaller<int (HttpCompatResource::*)(HttpServerConnection&, HttpRequest&, HttpResponse&)>::invoke(HttpServerConnection&, HttpRequest&, HttpResponse&) (D)
==31930==    by 0x806583B: operator() (Delegate.h:172)
==31930==    by 0x806583B: HttpServerConnection::onMessageComplete(http_parser*) (HttpServerConnection.cpp:67)
==31930==    by 0x8063E25: HttpConnection::staticOnMessageComplete(http_parser*) (HttpConnection.cpp:164)
==31930==    by 0x806E979: http_parser_execute (http_parser.c:1790)
==31930==    by 0x806405F: HttpConnection::onTcpReceive(TcpClient&, char*, int) (HttpConnection.cpp:177)
==31930==    by 0x8063E7F: MethodCaller<bool (HttpConnection::*)(TcpClient&, char*, int)>::invoke(TcpClient&, char*, int) (Delegate.h:83)
==31930==    by 0x80622C7: operator() (Delegate.h:172)
==31930==    by 0x80622C7: TcpClient::onReceive(pbuf*) (TcpClient.cpp:105)
==31930== 
==31930== Jump to the invalid address stated on the next line
==31930==    at 0x0: ???
==31930==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==31930== 

signal_handler: SIGSEGV - segmentation fault

```

@mikee47 Can you try the DNSCaptivePortal sample and check if I am the only one that experiences such issues?

**Comment by mikee47** [comment]
Can't check Linux ATM, but running under Windows confirms something is going wrong.

I browse to the device and get the initial webpage OK ("SMING captive portal") all well and good. But then this:

```
Starting program: R:\sming-v4\samples\DNSCaptivePortal/out/firmware/app.exe "--uart=0" --pause "--ipaddr=192.168.1.10" "--gateway=192.168.1.254" "--flashsize=4M"
[New Thread 21832.0xed0]
[New Thread 21832.0x4c50]
[New Thread 21832.0x40d8]
[New Thread 21832.0x514c]

Welcome to the Sming Host emulator

host_flashmem_init: Opened "flash.bin", size = 0x00400000
[New Thread 21832.0x4a00]
host_lwip_init: Initialising LWIP
** Npcap version 0.995, based on libpcap version 1.9.1-PRE-GIT
CUartServer::thread_routine: UART0 server listening on port 10000
host_lwip_init: gateway = 192.168.1.254, netmask = 255.255.255.0; using ip = 192.168.1.10
Using adapter: "Realtek PCIe GBE Family Controller"
host_lwip_init: MAC: 00:01:02:03:04:05
main: If required, you may start terminal application(s) now
pause: Hit ENTER to continue.
CUartServer::thread_routine: Uart #0 socket open

main: >> Starting Sming <<


Program received signal SIGSEGV, Segmentation fault.
0x00420587 in HttpResponse::freeStreams (this=this@entry=0x153ae9c) at Core/Network/Http/HttpResponse.cpp:172
172                             delete buffer;
(gdb)
(gdb) bt
#0  0x00420587 in HttpResponse::freeStreams (this=this@entry=0x153ae9c) at Core/Network/Http/HttpResponse.cpp:172
#1  0x004208aa in HttpResponse::reset (this=this@entry=0x153ae9c) at Core/Network/Http/HttpResponse.cpp:163
#2  0x00426bef in HttpServerConnection::onReadyToSendData (this=0x153ae08, sourceEvent=<optimized out>) at Core/Network/Http/HttpServerConnection.cpp:193
#3  0x00422655 in TcpConnection::onSent (this=this@entry=0x153ae08, len=134) at Core/Network/TcpConnection.cpp:125
#4  0x0042bd6b in TcpClient::onSent (this=0x153ae08, len=134) at Core/Network/TcpClient.cpp:175
#5  0x00421db7 in TcpConnection::internalOnSent (this=this@entry=0x153ae08, len=len@entry=134) at Core/Network/TcpConnection.cpp:589
#6  0x0042eb35 in operator() (__closure=0x0, tcp=0x45ca8c <memp_memory_TCP_PCB_base+492>, len=134, arg=0x153ae08) at Core/Network/TcpConnection.cpp:324
#7  TcpConnection::<lambda(void*, tcp_pcb*, uint16_t)>::_FUN(void *, tcp_pcb *, uint16_t) () at Core/Network/TcpConnection.cpp:325
#8  0x0040c6da in tcp_input ()
#9  0x00417429 in ip4_input ()
#10 0x00417ffa in ethernet_input ()
#11 0x00402a4e in pcapif_input ()
#12 0x68daaa53 in wpcap!pcap_lookupnet () from C:\WINDOWS\SysWOW64\npcap\wpcap.dll
#13 0x00402cfc in pcapif_poll ()
#14 0x00401a9f in host_lwip_service ()
#15 0x0043b60f in main (argc=6, argv=0x15317c0) at Arch/Host/Components/hostlib/startup.cpp:222
(gdb)
```

Serial console shows this:

```
5488401 UDP listen port 53
5488401 +TCP connection
5488401 '/' registered
5488401 '*' registered
7962761 onAccept state: 0 K=0
7962761 Free heap size=4294967295, K=0
7962761 +TCP connection
7962761 timeout updating: 70 -> 2
7962761 Opening connection. Total connections: 1
7962761 TcpServer onClient: 192.168.1.77

7962761 The headers are complete
7962761 Storing 17 bytes in stream
7962761 realloc 17 -> 171
7962761 Storing 25 bytes in stream
7962761 Storing 20 bytes in stream
7962761 Storing 24 bytes in stream
7962761 Storing 26 bytes in stream
7962761 Storing 2 bytes in stream
7962761 TCP onReadyToSendData: 1
7962761 TCP Written: 114, Available: 114, isFinished: 1, PushCount: 1 [TcpBuf: 958]
7962761 TcpClient stream finished
7962761 TCP received: 336 bytes
7962761 TCP onReadyToSendData: 1
7962761 TCP Written: 20, Available: 20, isFinished: 1, PushCount: 1 [TcpBuf: 938]
7963705 TcpClient stream finished
7965660 TCP sent: 134
```

**Comment by mikee47** [comment]
Not related to this PR, by the way - exactly the same result with develop.

**Comment by mikee47** [comment]
A couple of further related issues come to mind, which could also be addressed by this PR:

1. The emulator places internal flash data (i.e. PROGMEM, PSTR, FlashString, etc) into a completely separate address space from external flash data (accessed via `flashmem_*` calls). This may break existing code which attempts to use `flashmem_read`, for example, on a PSTR. I would suggest that good practice would be to consider them entirely separate, even on target hardware. At present it's not very easy to include custom data in external flash, but that will improve with the partition support.

2. It should be possible to continue using __attribute__((section)) on both Linux/Windows to place such  internal data into a separate section, then we can include further checks in the emulator. For example, we can ensure that `memcpy_P` only reads from genuine flash and writes to RAM. We might also find a way to ensure that a regular `memcpy` never accesses flash memory.

**Comment by slaff** [comment]
> Not related to this PR, by the way - exactly the same result with develop.

This PR #1716 should fix the segfault issue.

**Comment by slaff** [comment]
> A couple of further related issues come to mind, which could also be addressed by this PR:

@mikee47 What is the state of this PR? Shall I merge it? Or wait for more changes ?

**Comment by mikee47** [comment]
@slaff I think leave those for now, I'll take a look at that in a separate PR as it's going to be more complicated.

**Comment by slaff** [comment]
> I think leave those for now, I'll take a look at that in a separate PR as it's going to be more complicated.

Ok, shall I merge this PR as it is or close it and wait for other PRs related to this one?

**Comment by mikee47** [comment]
Let's merge it.

File: Sming/Wiring/FakePgmSpace.h [hunk 1]
```diff
@@ -170,18 +147,13 @@ extern "C"
 
 #else /* ICACHE_FLASH */
 
-#define PROGMEM
-
-#define PSTR(_str) (_str)
-#define _F(_str) (_str)
+#define PROGMEM __attribute__((aligned(4)))
```
Comment (slaff) [inline Sming/Wiring/FakePgmSpace.h]: This will break the compilation of some Arduino and other libraries that define PROGMEM as empty for platforms other than AVR or ESP8266. As long as redefinition is treated as error from the compiler. 
For example: https://github.com/SmingHub/Sming/blob/develop/Sming/Libraries/Adafruit_GFX/glcdfont.c#L10 has the following code:
```
#if defined(__AVR__)
 #include <avr/io.h>
 #include <avr/pgmspace.h>
#elif defined(__ESP8266_EX__)
 #include <WiringFrameworkDependencies.h>
#else
 #define PROGMEM
#endif
```
