### PR TITLE
Fix memory leak in MqttClient

### LINKED ISSUE #1740: Memory leak in MqttClient connect
It seems that that trying to connect with `MqttClient` causes a memory leak. When the MQTT broker is not reachable and then retrying regularly then at some point you run out of heap.

Should be easily reproducible with the sample `MqttClient_Hello`. While I used this exact code (basically only publish removed):
```
#include <user_config.h>
#include <SmingCore.h>

// If you want, you can define WiFi settings globally in Eclipse Environment Variables
#ifndef WIFI_SSID
#define WIFI_SSID "<ssid>" // Put you SSID and Password here
#define WIFI_PWD "<pw>"
#endif

// For testing purposes, try a few different URL formats
#define MQTT_URL1 "mqtt://attachix.com:1883"
#define MQTT_URL2 "mqtts://attachix.com:8883" // (Need ENABLE_SSL)
#define MQTT_URL3 "mqtt://frank:fiddle@192.168.100.107:1883"

#define MQTT_URL "mqtt://192.168.5.2:555"

//const Url url("192.168.5.2:555");

// Forward declarations
void startMqttClient();
void onMessageReceived(String topic, String message);

MqttClient mqtt;

Timer procTimer;

// Check for MQTT Disconnection
void checkMQTTDisconnect(TcpClient& client, bool flag)
{
if(flag == true) {
Serial.println("MQTT Broker Disconnected!!");
} else {
Serial.println("MQTT Broker Unreachable!!");
}

// Restart connection attempt after few seconds
procTimer.initializeMs(2 * 1000, startMqttClient).start(); // every 2 seconds
}

void onMessageDelivered(uint16_t msgId, int type)
{
Serial.printf("Message with id %d and QoS %d was delivered successfully.", msgId,
 (type == MQTT_MSG_PUBREC ? 2 : 1));
}

// Publish our message
void publishMessage()
{
if(mqtt.getConnectionState() != eTCS_Connected) {
startMqttClient(); // Auto reconnect
}

Serial.print("Let's publish message now. Memory free=");
Serial.println(system_get_free_heap_size());
mqtt.publish("main/frameworks/sming", "Hello friends, from Internet of things :)");

mqtt.publishWithQoS("important/frameworks/sming", "Request Return Delivery", 1, false,
onMessageDelivered); // or publishWithQoS
}

// Callback for messages, arrived from MQTT server
void onMessageReceived(String topic, String message)
{
Serial.print(topic);
Serial.print(":\r\n\t"); // Pretify alignment for printing
Serial.println(message);
}

// Run MQTT client
void startMqttClient()
{
procTimer.stop();

Serial.print("Let's publish message now. Memory free=");
Serial.println(system_get_free_heap_size());

// 1. [Setup]
if(!mqtt.setWill("last/will", "The connection from this device is lost:(", 1, true)) {
debugf("Unable to set the last will and testament. Most probably there is not enough memory on the device.");
}

mqtt.setCompleteDelegate(checkMQTTDisconnect);
mqtt.setCallback(onMessageReceived);

#ifdef ENABLE_SSL
mqtt.addSslOptions(SSL_SERVER_VERIFY_LATER);

#include <ssl/private_key.h>
#include <ssl/cert.h>

mqtt.setSslKeyCert(default_private_key, default_private_key_len, default_certificate, default_certificate_len,
  nullptr,
  /*freeAfterHandshake*/ false);

#endif

// 2. [Connect]
Url url(MQTT_URL);
Serial.printf("Connecting to \t%s\n", url.toString().c_str());
mqtt.connect(url, "esp8266");
mqtt.subscribe("main/status/#");
}

void onConnected(IPAddress ip, IPAddress netmask, IPAddress gateway)
{
// Run MQTT client
startMqttClient();
}

void init()
{
Serial.begin(SERIAL_BAUD_RATE); // 115200 by default
Serial.systemDebugOutput(true); // Debug output to serial

WifiStation.config(WIFI_SSID, WIFI_PWD);
WifiStation.enable(true);

// Run our method when station was connected to AP (or not connected)
WifiEvents.onStationGotIP(onConnected);
}
```

Output is this:
```
--- Miniterm on /dev/ttyUSB0  115200,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ota1 not set
ota2 not set
>> 0x3f␀*qURQ���␃�␛�N�{��o|�␌$␌dll ␃␜b�␒␂␌�|␃r�␂$�o�␌�n�␀␄l ␃��s�p��$␛�␌��j16078377 Station configuration is: hsync
mode : sta(84:0d:8e:a7:84:44)
add if0
16086758 mode: 0 -> 3

scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 9
cnt 

connected with hsync, channel 11
dhcp client start...
16243552 connect to ssid hsync, channel 11

ip:192.168.2.28,mask:255.255.255.0,gw:192.168.2.1
19105045 ip:192.168.2.28,mask:255.255.255.0,gw:192.168.2.1
19105349 

Let's publish message now. Memory free=49864
Connecting to mqtt://192.168.5.2:555/
pm open,type:2 0
MQTT Broker Unreachable!!
Let's publish message now. Memory free=48968
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=48504
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=48080
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47680
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47200
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=46760
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=46520
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=46240
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=45984
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
...
Let's publish message now. Memory free=2456
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=2200
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=1968
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=1688
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=1432
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=1200
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=920
Connecting to mqtt://192.168.5.2:555/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=664
Connecting to mqtt://192.168.5.2:555/
E:M 136
E:M 328
state: 5 -> 2 (1c0)
rm 0
pm close 7
1874188867 disconnect from ssid hsync, reason 1

reconnect
state: 2 -> 0 (0)
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 9
cnt 

connected with hsync, channel 11
E:M 1200
dhcp client start...
E:M 440
1875347370 connect to ssid hsync, channel 11

E:M 520
pm_err,flash_tmp alloc fail
```

Done on Sming 3.8.0 on an ESP12-F.

### PR DESCRIPTION
**Pull request by mikee47**
If request queue is full due to non-responsive server then allocated message will never be freed.

A new `MqttRequestQueue` class handles all message queueing. Only one connect message may be queued, and it always takes priority over others.

Should fix #1740

### CODE REVIEW

File: Sming/Core/Network/MqttClient.cpp [hunk 1]
```diff
@@ -225,6 +225,11 @@ bool MqttClient::connect(const Url& url, const String& clientName, uint32_t sslO
 		}
 	}
 
+	if(requestQueue.full()) {
```
Comment (slaff) [inline Sming/Core/Network/MqttClient.cpp]: The suggested change is improvement to what we had but I was wondering if we can improve it further without too much overhead.
What I mean is the following:  While piling X normal publish messages in the queue is a good idea piling X connect messages is not. So my suggestion would be to look in the queue for connect message and if found replace it with the new connect message. A connect message should be the first to be dequeued. There should be max one connect message in the queue.

**Comment by verybadsoldier** [comment]
This patch stops the reconnect attempts entirely for me. The first tries are there but are still decreasing memory (which is expected as far as I understand the change). Then the queue check kicks in no more connection attempts happen.
<Todo Log>

File: Sming/Core/Network/MqttClient.cpp [hunk 2]
```diff
@@ -286,13 +280,13 @@ bool MqttClient::subscribe(const String& topic)
 		return false;
 	}
 
-	mqtt_message_t* message = (mqtt_message_t*)malloc(sizeof(mqtt_message_t));
-	mqtt_message_init(message);
-	message->common.type = MQTT_TYPE_SUBSCRIBE;
-	message->subscribe.topics = (mqtt_topicpair_t*)malloc(sizeof(mqtt_topicpair_t));
-	memset(message->subscribe.topics, 0, sizeof(mqtt_topicpair_t));
+	mqtt_message_t message;
```
Comment (slaff) [inline Sming/Core/Network/MqttClient.cpp]: You are creating here a local variable and then you are passing the address of that local variable to be used later from the requestQueue. I am not sure this is a good idea. By the time the message is dequeued the memory address will most certainly point to something unexpected.

Comment (mikee47) [reply Sming/Core/Network/MqttClient.cpp]: I've taken another go at this, much happier with it.

Comment (slaff) [reply Sming/Core/Network/MqttClient.cpp]: > I've taken another go at this, much happier with it.

Now it looks much better :)

**Comment by slaff** [comment]
@mikee47 Can you try again with the latest code from this PR?

**Comment by mikee47** [comment]
@verybadsoldier Can you try again with the latest code from this PR?

File: Sming/Core/Network/MqttClient.cpp (hunk 2 above)
Comment (slaff) [reply Sming/Core/Network/MqttClient.cpp]: On the Host it works like charm.

```
55018194 MQTT replacing connect message
MQTT Broker Disconnected!!
Connecting to 	mqtt://attachix.zom:1883/
57112580 MQTT replacing connect message
MQTT Broker Disconnected!!
Connecting to 	mqtt://attachix.zom:1883/
59217835 MQTT replacing connect message
MQTT Broker Disconnected!!
Connecting to 	mqtt://attachix.zom:1883/
61317774 MQTT replacing connect message
MQTT Broker Disconnected!!
...
```
and the final summary
```
==5606== LEAK SUMMARY:
==5606==    definitely lost: 0 bytes in 0 blocks
==5606==    indirectly lost: 0 bytes in 0 blocks
==5606==      possibly lost: 0 bytes in 0 blocks
```

**Comment by verybadsoldier** [comment]
Sorry but still leaking for me:
```
Connecting to 	mqtt://192.165.5.3:883/
MQTT Broker Unreachable!!
Let's publish message now. Memory free=49176
pm open,type:2 0
Connecting to 	mqtt://192.165.5.3:883/
27310057 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=48472
Connecting to 	mqtt://192.165.5.3:883/
36385085 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=48296
Connecting to 	mqtt://192.165.5.3:883/
45760119 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=48112
Connecting to 	mqtt://192.165.5.3:883/
54960107 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47936
Connecting to 	mqtt://192.165.5.3:883/
64060168 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47752
Connecting to 	mqtt://192.165.5.3:883/
73111161 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47584
Connecting to 	mqtt://192.165.5.3:883/
82360126 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47392
Connecting to 	mqtt://192.165.5.3:883/
91535142 MQTT replacing connect message
```

**Comment by mikee47** [comment]
Wait a bit, the queue holds 10 messages so memory will stop incrementing once that's full.

**Comment by verybadsoldier** [comment]
Ah, thanks, right. Stable for a while then one drop later. But that might have had other reasons.
```
Let's publish message now. Memory free=47584
Connecting to 	mqtt://192.165.5.3:883/
82360126 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47392
Connecting to 	mqtt://192.165.5.3:883/
91535142 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47232
Connecting to 	mqtt://192.165.5.3:883/
100635114 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
109835156 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
118960126 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
128260198 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
137260130 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
146510155 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
155635159 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
165010131 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
174185476 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
183460184 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
192585184 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
201860123 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
211010409 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
220210126 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
229310153 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
238435150 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
247560185 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
256610119 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
265810128 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
275010131 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
284335185 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
293335162 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
302735126 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
312160129 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
321285200 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
330435127 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
339560148 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
348685130 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
358085117 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
367385196 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
376560152 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
385835125 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
395110124 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
404385160 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
413710162 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
423010131 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
432285201 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
441310156 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
450360134 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
459535135 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
468935117 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
478135174 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
487385197 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
496310119 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
505510197 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=47064
Connecting to 	mqtt://192.165.5.3:883/
514535152 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=46888
Connecting to 	mqtt://192.165.5.3:883/
523735191 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=46888
Connecting to 	mqtt://192.165.5.3:883/
532735142 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=46888
Connecting to 	mqtt://192.165.5.3:883/
541760153 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=46888
Connecting to 	mqtt://192.165.5.3:883/
550910125 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=46888
Connecting to 	mqtt://192.165.5.3:883/
560310159 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=46888
Connecting to 	mqtt://192.165.5.3:883/
569485131 MQTT replacing connect message
MQTT Broker Unreachable!!
Let's publish message now. Memory free=46888
Connecting to 	mqtt://192.165.5.3:883/
578560152 MQTT replacing connect message
```

**Comment by slaff** [comment]
>  Stable for a while then one drop later. But that might have had other reasons.

The first is expected and the second is something that I have noticed multiple times. The the updated PR addresses the memory leak issue and I plan to merge it later today or tomorrow if there are no objections.
